name: mushagaeshi_binary_editor
description: Mushagaeshi Binary Editor, a desktop hexadecimal comparison app.
publish_to: none
version: 0.5.0+5
environment:
  sdk: '>=3.13.3 <4.0.0'
dependencies:
  crypto: ^3.0.7
  desktop_drop: 0.8.4
  file_selector: 1.1.0
  flutter:
    sdk: flutter
  path: 1.9.1
  package_info_plus: ^8.3.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  window_manager: 0.5.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
